import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import dashboardRouter from "./dashboard";
import inventoryRouter from "./inventory";
import branchesRouter from "./branches";
import purchasesRouter from "./purchases";
import productionRouter from "./production";
import stockRouter from "./stock";
import salesRouter from "./sales";
import paymentsRouter from "./payments";
import reconciliationRouter from "./reconciliation";
import cashInOutletRouter from "./cash-in-outlet";
import hrRouter from "./hr";
import customersRouter from "./customers";
import accountsRouter from "./accounts";
import companyRouter from "./company";
import auditRouter from "./audit";
import publicInvoicesRouter from "./publicInvoices";
const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(dashboardRouter);
router.use(inventoryRouter);
router.use(branchesRouter);
router.use(purchasesRouter);
router.use(productionRouter);
router.use(stockRouter);
router.use(salesRouter);
router.use(paymentsRouter);
router.use(reconciliationRouter);
router.use(cashInOutletRouter);
router.use(hrRouter);
router.use(customersRouter);
router.use(accountsRouter);
router.use(companyRouter);
router.use(auditRouter);
router.use(publicInvoicesRouter);

export default router;
