import { Router, type IRouter } from "express";
import healthRouter from "./health";
import periodsRouter from "./periods";
import authRouter from "./auth";
import dashboardRouter from "./dashboard";
import inventoryRouter from "./inventory";
import branchesRouter from "./branches";
import purchasesRouter from "./purchases";
import productionRouter from "./production";
import stockRouter from "./stock";
import inventoryBatchesRouter from "./inventory-batches";
import salesRouter from "./sales";
import paymentsRouter from "./payments";
import reconciliationRouter from "./reconciliation";
import cashInOutletRouter from "./cash-in-outlet";
import hrRouter from "./hr";
import customersRouter from "./customers";
import accountsRouter from "./accounts";
import journalRouter from "./journal";
import gstRouter from "./gst";
import companyRouter from "./company";
import auditRouter from "./audit";
import publicInvoicesRouter from "./publicInvoices";
import invoiceShareLinksRouter from "./invoiceShareLinks";
import quotationsRouter from "./quotations";
import publicQuotationsRouter from "./publicQuotations";
import quotationShareLinksRouter from "./quotationShareLinks";
import pdfGenRouter from "./pdfGen";
import returnsRouter from "./returns";
import bomRouter from "./bom";
import reportsRouter from "./reports";
import financialReportsRouter from "./financialReports";
import searchRouter from "./search";
import storageRouter from "./storage";
import rentRouter from "./rent";
import backupRouter from "./backup";
import assetsRouter from "./assets";
import importsRouter from "./imports";
const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(dashboardRouter);
// assetsRouter must precede inventoryRouter: inventory's GET /assets/:id would
// otherwise swallow /assets/categories, /assets/purchases, /assets/summary, …
router.use(assetsRouter);
router.use(inventoryRouter);
router.use(branchesRouter);
router.use(purchasesRouter);
router.use(productionRouter);
router.use(stockRouter);
router.use(inventoryBatchesRouter);
router.use(salesRouter);
router.use(paymentsRouter);
router.use(reconciliationRouter);
router.use(cashInOutletRouter);
router.use(hrRouter);
router.use(customersRouter);
router.use(accountsRouter);
router.use(journalRouter);
router.use(periodsRouter);
router.use(gstRouter);
router.use(companyRouter);
router.use(auditRouter);
router.use(publicInvoicesRouter);
router.use(invoiceShareLinksRouter);
router.use(quotationsRouter);
router.use(publicQuotationsRouter);
router.use(quotationShareLinksRouter);
router.use(pdfGenRouter);
router.use(returnsRouter);
router.use(bomRouter);
router.use(reportsRouter);
router.use(financialReportsRouter);
router.use(searchRouter);
router.use(storageRouter);
router.use(rentRouter);
router.use(backupRouter);
router.use(importsRouter);

export default router;
