kind = "mobile"
previewPath = "/employee-app/"
title = "Marlin Employee App"
version = "1.0.0"
id = "artifacts/employee-app"
router = "expo-domain"

[[services]]
name = "expo"
ensurePreviewReachable = "/status"
paths = [ "/employee-app/" ]
localPort = 25991

[services.development]
run = "pnpm --filter @workspace/employee-app run dev"

[services.env]
PORT = "25991"
BASE_PATH = "/employee-app/"
